import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import newStyles from "../styles/Home.module.scss";

const testData = [
  {
    name: "#금융",
  },
  {
    name: "#MBTI",
  },
  {
    name: "#테스트",
  },
  {
    name: "#토이 프로젝트",
  },
  {
    name: "#스타트업",
  },
  {
    name: "#이건 테스트",
  },
  {
    name: "#이것도 테스트",
  },
  {
    name: "#디자인 추가필요",
  },
];

const testPost = [
  {
    imgSrc:
      "https://velog.velcdn.com/images/eunbinn/post/c8d8a1e4-4fa0-49df-bb86-f78a7818b7de/image.png",
    title: "[번역] 입문자를 위한 Axios vs Fetch",
    description:
      "Axios와 Fetch API에 대해 소개하고 비교하는 글입니다. 제목에서도 알 수 있듯이 설치방법 부터 간단한 성능 비교까지 기본적인 내용들을 다루고 있습니다.",
    date: "2022년 4월 29일",
  },
  {
    imgSrc:
      "https://velog.velcdn.com/images/gomjellie/post/cda9fed2-1bcb-4032-867f-941dd79c5a8a/image.jpg",
    title: "[번역] 입문자를 위한 Axios vs Fetch",
    description:
      "Axios와 Fetch API에 대해 소개하고 비교하는 글입니다. 제목에서도 알 수 있듯이 설치방법 부터 간단한 성능 비교까지 기본적인 내용들을 다루고 있습니다.",
    date: "2022년 4월 29일",
  },
  {
    imgSrc:
      "https://velog.velcdn.com/images/rat8397/post/458825c1-e8f0-4ced-b406-361d8f9183d8/image.gif",
    title: "[번역] 입문자를 위한 Axios vs Fetch",
    description:
      "Axios와 Fetch API에 대해 소개하고 비교하는 글입니다. 제목에서도 알 수 있듯이 설치방법 부터 간단한 성능 비교까지 기본적인 내용들을 다루고 있습니다.",
    date: "2022년 4월 29일",
  },
  {
    imgSrc:
      "https://velog.velcdn.com/images/kimjimin4471/post/e9452550-4ddd-4e59-ba5f-70a18b5e40fa/image.png",
    title: "[번역] 입문자를 위한 Axios vs Fetch",
    description:
      "Axios와 Fetch API에 대해 소개하고 비교하는 글입니다. 제목에서도 알 수 있듯이 설치방법 부터 간단한 성능 비교까지 기본적인 내용들을 다루고 있습니다.",
    date: "2022년 4월 29일",
  },
];

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>9zik :: 세상의 모든 프로젝트 저장소</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={newStyles.mainLogo}>9zik</h1>
        <div className={newStyles.main__logo__title}>
          세상의 모든 프로젝트 저장소
        </div>
        <div className={newStyles.mainSearchWrap}>
          <div className={newStyles.mainSearchNation}>검색</div>
          <div className={newStyles.mainSearch}>
            <input
              className={newStyles.mainSearchForm}
              placeholder="프로젝트명 ..."
              onChange={(e) => setName(e.target.value)}
              onKeyDown={(e) => {
                handleKeyPress(e);
              }}
            />
            <Image
              className="SearchButton"
              src="/search-btn.svg"
              alt="search-btn"
              width={24}
              height={21}
            />
          </div>
        </div>
        <div className={newStyles.category}>
          {testData.map((data) => {
            return <div className={newStyles.category__btn}>{data.name}</div>;
          })}
        </div>
        <div className={newStyles.project__wrap}>
          {testPost.map((data) => {
            return (
              <div className={newStyles.project__post}>
                <div className={newStyles.project__post__thumbnail}>
                  <img src={data.imgSrc} />
                </div>
                <div className={newStyles.project__post__content}></div>
                <div className={newStyles.project__post__content}>
                  <h4>{data.title}</h4>
                  <div className={newStyles.description__wrapper}>
                    <p>{data.description}</p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
